apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: trials
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      imagePullSecrets:
      - name: mynodepass
      containers:
      - name: nodealpine
        image: 255757214348.dkr.ecr.us-east-1.amazonaws.com/noderepo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  externalIPs:
  - x.x.x.x.x
